### ISSUE TITLE
Multi-Shipment ScanForm Error

### ISSUE THREAD

**Issue by shanecleveland** [EasyPost/easypost-python#78] opened 2019-01-10 23:03 UTC
I want to pull multiple shipment ids from a database and request a scan form, but I receive an error when attempting the request when the array of objects containing the shipment ids is assigned to variable:

    shipments = [{'id': 'shp_504...'}, {'id': 'shp_6e0...'}]
    import json
    manifest = json.dumps(shipments)

    scan_form = easypost.ScanForm.create(shipments=manifest)

I only receive the error: Error: We're sorry, something went wrong. If the problem persists please contact Support.

Support cannot explain and suggested I submit this issue.

**Comment by att14** [comment] 2019-01-10 23:18
You shouldn't need to `json.dumps` before passing it to `ScanForm.create`. `ScanForm.create` takes a list of dictionaries in the `shipments` kwarg.

**Comment by att14** [comment] 2019-01-10 23:44
I was able to generate a scan form using `easypost.ScanForm.create(shipments=[{"id": s.id}])` without issue.

Looking at your request logs I'm seeing non-500 responses when you are using a list instead of a string.

**Comment by shanecleveland** [comment] 2019-01-10 23:48
I can also do what you are suggesting. What I am not able to do is:

    shp_id = s.id
    easypost.ScanForm.create(shipments=shp_id)

That's what I need to do in order to include n number of shipments.

**Comment by shanecleveland** [comment] 2019-01-11 19:10
Hello, just wondering if you have been able to try what I have suggested above? Thank you!

**Comment by att14** [comment] 2019-01-12 19:58
I have tested that `easypost.ScanForm.create(shipments=[{"id": s.id}])` works as intended. It seems like you are trying to add `delivered` shipments to a scan from which will not work either, but it shouldn't result in a 500. I have confirmed that supplying a string as the `shipments` kwarg does result in a 500. Otherwise, in your logs I am seeing either 200 or 422.

I opened a ticket on our backend for the 500 resulting from supplying the incorrect type to this kwarg. However, this is a problem with the server not the client, so I am going to close this.

**Closed by att14** 2019-01-12 19:58 UTC

**Comment by att14** [comment] 2019-01-14 18:23
```
shp_id = [{"id": "shp_1234..."}]
easypost.ScanForm.create(shipments=shp_id)
```

is identical to,

```
easypost.ScanForm.create(shipments=[{"id": s.id}])
```

So it should work. You might receive non-500 errors, e.g. 422 with a specific error message, that would not allow you to create the scan form.

**Comment by shanecleveland** [comment] 2019-01-15 01:12
Thank you. Something changed, and it is now working and giving more specific error messages. It was not doing that until today.
